### PR TITLE
Update download_data.sh

### PR DESCRIPTION
**Pull request by melvinjosej**
Fixes the download script to bring it back to the state in https://github.com/google-research/xtreme/pull/15/files

### CODE REVIEW

**Comment by stefan-it** [comment]
Can confirm that it's working now :+1:

**Comment by JunjieHu** [comment]
In my local environment, my previous script worked just fine. "unzip -qq $DIR/AmazonPhotos.zip -d $DIR/" would create a sub-folder called "panx_dataset" under $DIR. 

The current script doesn't work for me in my machine -- it creates a duplicated sub-folder. I guess this might be due to the local environment. 

I searched a bit, it is safer to add "-j" option to extract only files and save to the directory by "-d", i.e.,  "unzip -qq -j $DIR/AmazonPhotos.zip -d $base_dir" which works for me in my machine. @melvinjosej could you add "-j" to the unzip command?

**Comment by melvinjosej** [comment]
@JunjieHu, I made the change. Can you check now?

**Comment by JunjieHu** [comment]
@melvinjosej Yes! Now it works in my local machine.

**Pull request merged**
