### PR TITLE
Fix typo in preprocess_panx.sh

### PR DESCRIPTION
**Pull request by blazejdolicki**

### CODE REVIEW

**Comment by blazejdolicki** [comment]
@googlebot I signed it!

**Comment by blazejdolicki** [comment]
I added my github username to the CLA, maybe it will work now.

**Comment by blazejdolicki** [comment]
I added my github username to the CLA, maybe it will work now.

**Comment by sebastianruder** [comment]
Hey @blazejdolicki, I just checked. The bot can find a CLA for your GitHub username but not for the email address you used for the commit. Could you sign the CLA also with that email address?

**Comment by blazejdolicki** [comment]
I created a new pull request with the right email, see https://github.com/google-research/xtreme/pull/33 I'm closing this one.

**Pull request closed without merging**
